### ISSUE TITLE
Support for custom protocols in Electron

### ISSUE THREAD

**Issue by waywardmonkeys** [paulcbetts/electron-compile#3]
Some projects use custom protocols to simplify loading (like handling some path management). How should they best integrate with ``electron-compile``?

**Comment by paulcbetts** [comment]
@waywardmonkeys Right now that isn't so easy, we should export `availableCompilers` as well as pull out some of the code around https://github.com/paulcbetts/electron-compile/blob/master/src/main.js#L63 and make it more modular

**Comment by paulcbetts** [comment]
This is fixed, it should be easy to write your own compiler chain now
