### ISSUE TITLE
Use tsconfig for TypeScript compiler configuration

### ISSUE THREAD

**Issue by waywardmonkeys** [paulcbetts/electron-compile#5]
It'd be nice if the ``tsconfig.json`` data could be used when loading a package rather than setting it up in advance.

**Comment by paulcbetts** [comment]
Agree - there are a ton of compiler options that are flat-out being left out at the moment, this is why we're at 0.2!

**Comment by paulcbetts** [comment]
This should be fixed by #9

**Comment by waywardmonkeys** [comment]
This isn't fixed by #9 since #9 doesn't use the ``tsconfig.json`` file. :)

Summoning the ghost of @basarat ...

**Comment by paulcbetts** [comment]
It does, because assumedly you could configure TypeScript to accept any number of JSON configuration files yourself :)

**Comment by basarat** [comment]
> you could configure TypeScript to accept any number of JSON configuration files yourself

:+1:

**Comment by wasd171** [comment]
Is it possible to use with `electron-forge` or it's for direct use only? `tsconfig.json` and `.compilerc` are almost identical, which is not convinient
